---
# pre-commit install
# pre-commit run --all-files
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  # * Top level
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  # * Sync dependencies
  - repo: https://github.com/mxr/sync-pre-commit-deps
    rev: v0.0.1
    hooks:
      - id: sync-pre-commit-deps

  # * Pyproject-fmt
  # NOTE: This is pretty different from prettier formatting.
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "1.5.3"
    hooks:
      - id: pyproject-fmt
        args: ["--indent=4", "--keep-full-version"]
        files: ^pyproject.toml$

  # * Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.7"
    hooks:
      - id: prettier
        alias: markdownlint
        stages: [commit]
        additional_dependencies:
          - prettier-plugin-toml
        # defer to project-fmt for pyproject.toml
        exclude: pyproject.toml|^requirements/lock/.*[.]yml|^.copier-answers.ya?ml|^tests/lnpy_data/sample_data.json

  # * Markdown
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.11.0
    hooks:
      - id: markdownlint-cli2
        alias: markdownlint
        args: ["--style prettier"]

  # * Linting
  # To be replace by ruff analog when I find one ...
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.16.0"
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==23.11.0
        # exclude: ^README.md
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.1.8"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-ruff
        additional_dependencies: [ruff==0.1.8]
        # Replace with builtin if/when available
      - id: nbqa
        alias: nbqa-ruff-format
        name: nbqa-ruff-format
        additional_dependencies: [ruff==0.1.8]
        args: ["ruff format --force-exclude"]

  # * Spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        types_or: [python, rst, markdown, cython, c, jupyter]
        additional_dependencies: [tomli]
        args: [-I, docs/spelling_wordlist.txt]
        exclude: "^examples"

  # * Commit message
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # * Manual Linting ------------------------------------------------------------
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        stages: [manual]
        args: [--py38-plus]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade]
        stages: [manual]
        args: [--py38-plus]
