name: thermoextrap-env
channels:
  - conda-forge
  - wpk-nist
dependencies:
  - python>=3.8
  - sympy
  - numpy
  - scipy
  - xarray
#  - openmm
  - cmomy>=0.1.9
  - custom-inherit
  - attrs
  - pymbar<4.0
  - pip
  - pip:
      - tensorflow
      - tensorflow-probability
      - gpflow
# prefix: /Users/wpk/miniforge3/envs/gpflow_test
